### ISSUE TITLE
我尝试的时候类型报错

### ISSUE THREAD

**Issue by 2234839** [justjavac/deno_cheerio#1]
![图片](https://user-images.githubusercontent.com/28727933/103639381-3e57fe00-4f89-11eb-9b7c-29845041536c.png)
---
我的权宜之计
![图片](https://user-images.githubusercontent.com/28727933/103640107-6a27b380-4f8a-11eb-88ba-d6f7268e57b1.png)

**Comment by justjavac** [comment]
安装 deno vscode 插件

**Comment by 2234839** [comment]
> 
> 
> 安装 deno vscode 插件
是指`deno-vscode`吗

我之前有安装这个 ![图片](https://user-images.githubusercontent.com/28727933/103716695-a1d04300-4ffe-11eb-89dc-7ab2aed78147.png)
刚刚尝试了 
![图片](https://user-images.githubusercontent.com/28727933/103716806-dc39e000-4ffe-11eb-921b-fa7dd0c8c86f.png)
还是一样的报错

**Comment by justjavac** [comment]
这个远程载入 types 好像有 bug，试试 canary 版

**Comment by 2234839** [comment]
> 
> 
> 这个远程载入 types 好像有 bug，试试 canary 版

![图片](https://user-images.githubusercontent.com/28727933/103746920-cfd47800-503c-11eb-9e9d-f8aafd078bc4.png)
使用这个版本虽然没有报错，但类型还是不对

**Comment by justjavac** [comment]
果然是我的问题，修复了 https://github.com/justjavac/deno_cheerio/commit/097ad957edc3f620f10afe12cc5d0354f6377ef8

运行 `deno cache --reload mod.ts` 再试一下
