### ISSUE TITLE
How to access CheerioElement, CheerioStatic, etc.?

### ISSUE THREAD

**Issue by shah** [justjavac/deno_cheerio#2]
This is a great library @justjavac! Thanks for putting it together.

I've been using `deno_cheerio` successfully for many months now but recently something changed and I'm not able to access `CheerioElement`, `CheerioStatic`, and similar.

For example, until last week this worked:

```typescript
// @deno-types="https://cdn.jsdelivr.net/gh/justjavac/deno_cheerio/cheerio.d.ts"
import cheerio from "https://dev.jspm.io/cheerio/index.js";

export interface HtmlImage {
  readonly src?: string;
  readonly alt?: string;
  readonly width?: number | string;
  readonly height?: number | string;
  readonly imageElem: CheerioElement;
}
```

Now, however, after the latest update I'm seeing this problem:

```bash
TS2304 [ERROR]: Cannot find name 'CheerioElement'.
    elem: CheerioElement,
          ~~~~~~~~~~~~~~
```

Any ideas on how I can fix that issue?
I just tried the following, too:

```typescript
  readonly imageElem: cheerio.CheerioElement;
```

But that did not work either, I get this error:

```bash
error: TS2503 [ERROR]: Cannot find namespace 'cheerio'.
  readonly imageElem: cheerio.CheerioElement;
                      ~~~~~~~
```

Any help would be appreciated. 
Thanks again for the great work!

**Comment by geovlazar** [comment]
@justjavac Thanks for providing the fix, it works locally but we are wondering when this fix will be available on `https://dev.jspm.io/cheerio/index.js`. Or is there a way to us directly use this library through GitHub CDN?

**Comment by geovlazar** [comment]
@justjavac  We updated the code with a pinnable version of cheerio `https://cdn.jsdelivr.net/gh/justjavac/deno_cheerio@v0.1.0/cheerio.d.ts`. This fixed our problem now and many thanks for this update.
