### ISSUE TITLE
Why create a separate project instead of forking/patching cheerio's repo?

### ISSUE THREAD

**Issue by pseudosavant** [justjavac/deno_cheerio#4]
Thanks for making so I can use Cheerio with Deno!

I'm interested in getting the mainline Cheerio to work with Deno out-of-the-box. Is there a reason this was done as a separate `deno_cheerio` project and not forked from the main Cheerio project?

**Comment by justjavac** [comment]
https://github.com/cheeriojs/cheerio/issues/1442
