### ISSUE TITLE
https://dev.jspm.io/cheerio/index.js not working

### ISSUE THREAD

**Issue by alan-francis** [justjavac/deno_cheerio#5]
Currently the url [https://dev.jspm.io/cheerio/index.js](url) is showing the error - "Internal error on package lookup.". Is there any alternate method to run this? Thanks in advance

**Comment by justjavac** [comment]
```ts
import * as cheerio from "https://esm.sh/cheerio";

const $ = cheerio.load('<h2 class="title">Hello world</h2>');

$("h2.title").text("Hello Deno!");
$("h2").addClass("deno");

console.log($.html());
```

**Comment by justjavac** [comment]
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/359395/174972094-b9bf4f6c-9932-45be-bac8-03f9e0358a86.png">

**Comment by alan-francis** [comment]
@justjavac : Thank you

**Comment by alan-francis** [comment]
@justjavac : We are running in a deno environment and are facing some issues with this like:

`error: TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'Record<symbol, unknown>'.
  Property '["https://deno.land/std@0.142.0/node/internal/crypto/_keys.ts".kKeyType]' does not exist on type 'Record<symbol, unknown>'.
    obj != null && (obj as Record<symbol, unknown>)[kKeyType] !== undefined
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.142.0/node/internal/crypto/_keys.ts:8:20`

Thanks in advance

**Comment by justjavac** [comment]
```
deno 1.23.0 (release, x86_64-apple-darwin)
v8 10.4.132.5
typescript 4.7.2
```

**Comment by justjavac** [comment]
playground: https://dash.deno.com/playground/deno-cheerio-issue-5
